const Api = {
    SIGN_IN: "https://manasthali-backend.onrender.com/users/login",
    SIGN_UP: "https://manasthali-backend.onrender.com/users/register", 
    SUBMIT_QUIZ: "https://manasthali-backend.onrender.com/quiz/submit",
    FORGOT_PASSWORD: "https://manasthali-backend.onrender.com/users/forgot-password",
    VERIFY_OTP:"https://manasthali-backend.onrender.com/users/verify-otp",
    SERVER_URL:"https://manasthali-backend.onrender.com",
    RESET_PASSWORD:"https://manasthali-backend.onrender.com/users/reset-password",
    COMMUNITY_URL:"https://manasthali-backend.onrender.com/communities/view",
    CHECK_EMAIL:"https://manasthali-backend.onrender.com/users/email",
    CHECK_USERNAME:"https://manasthali-backend.onrender.com/users/username",
    COMMUNITY_GET_URL:"https://manasthali-backend.onrender.com/communities/viewAll",
    CREATE_GROUP:"https://manasthali-backend.onrender.com/groups/create",
    ADMIN_LOGIN:"https://manasthali-backend.onrender.com/admin/login",
    GET_POST_EXCEPT_USER:"https://manasthali-backend.onrender.com/posts/all-posts",
    GET_COMMUNITY_POST:"https://manasthali-backend.onrender.com/posts/getCommunityPosts",
    GET_USER_POST:"https://manasthali-backend.onrender.com/posts/getUserPosts",
    GET_DAILY_CHALLENGE:"https://manasthali-backend.onrender.com/challenge/daily-challenge",
    SEND_NOTIFICATION:"https://manasthali-backend.onrender.com/notifications/notifications",
    BASIC_POST_ROUTE:"https://manasthali-backend.onrender.com/posts/posts",
    ADD_COMMENT:"https://manasthali-backend.onrender.com/comments/addComment",
    GET_COMMUNITY_USERS:"https://manasthali-backend.onrender.com/users/get-community-users",
    SEND_MESSAGE:"https://manasthali-backend.onrender.com/message/send",
    READ_MESSAGE:"https://manasthali-backend.onrender.com/message/read",
    JOINED_LIST:"https://manasthali-backend.onrender.com/groups/view/joinedList",
};

export default Api;